name: 02 - Auto PR a develop (si "integrar")

on:
  push:
    branches:
      - 'feature/**'
      - 'feat/**'
      - 'historia**'

permissions:
  contents: write
  pull-requests: write

jobs:
  auto_pr:
    name: Crear/actualizar PR -> develop
    if: contains(github.event.head_commit.message, 'integrar')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Autenticar GH CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh --version
          gh auth status || echo "$GH_TOKEN" | gh auth login --with-token

      - name: Crear PR si no existe
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          set -e
          COUNT=$(gh pr list --head "$BRANCH_NAME" --base develop --state open --json number --jq 'length')
          if [ "$COUNT" -eq 0 ]; then
            gh pr create --head "$BRANCH_NAME" --base develop \
              --title "Auto PR: $BRANCH_NAME → develop" \
              --body "Creado automáticamente al detectar 'integrar' en el commit."
          else
            echo "PR ya existe para $BRANCH_NAME -> develop."
          fi

      - name: Activar auto-merge (opcional)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          PR=$(gh pr list --head "$BRANCH_NAME" --base develop --state open --json number --jq '.[0].number')
          if [ -n "$PR" ]; then
            # --merge hace merge commit; usa --squash si prefieres squash
            gh pr merge "$PR" --merge --auto || echo "Auto-merge pendiente de checks/permissions."
          fi
