name: Pipeline MediSupply-Backend
on:
  push:
    branches: [ main ]
jobs:
  Mi-primer-job:
    name: Mi primer job
    runs-on: ubuntu-latest
    steps:
    - name: Imprimir 
      env:
        MI_VARIABLE: Hola mundo backend
      run: |
        echo $MI_VARIABLE.